### ISSUE TITLE
RGB LED on PIN 48 not working?

### ISSUE THREAD

**Issue by PBrunot** [vcc-gnd/YD-ESP32-S3#1]
I am unable to get the RGB LED to work on  YD-ESP32-S3 N8R2 2022-V1.3 with standard Micropython and recent Micropython with NeoPixel library. Oscilloscope attached to GPIO48 shows no 800 KHz output.

Another user has the same issue, with board V1.4.

Is this a known problem ? Any workaround ?

See for more details : https://github.com/orgs/micropython/discussions/11097

**Comment by PBrunot** [comment]
I think I have a defective ESP32 because the GPIO 48 is not outputting any signal, and if I connect NeoPixel on board to GPIO 10, it works fine.

**Comment by mikadoryu** [comment]
First of all, do I solder the rgb pads that connect it to pin 48? I had the same problem that the rgb led did not work until I had to activate the led.
![PIC001](https://user-images.githubusercontent.com/8473292/228708932-598b6c09-4e81-416f-8ec5-8f774c8842e7.JPG)

**Comment by tyg6** [comment]
@mikadoryu @PBrunot I had the same problem, could you please explain more simply how to activate the led? Many thanks!
![esp32-s3-rgb-led](https://github.com/vcc-gnd/YD-ESP32-S3/assets/5326919/1bb184cb-723a-4cfb-a193-c6590f4a3dac)

**Comment by PBrunot** [comment]
@tyg6  : you just need to add a bit of solder on the jumper below the RGB letters with your soldering pan, so that the circuit to the NeoPixel is closed. From your photo there is a gap between the two jumpers pins, so the NeoPixel will not work without this addition.

**Comment by tyg6** [comment]
@PBrunot Thanks for your quick reply! Got your point!

![esp32-s3-rgb-led-2](https://github.com/vcc-gnd/YD-ESP32-S3/assets/5326919/f59179bf-b78f-43fd-a62c-667438a7af99)

**Comment by tyg6** [comment]
It works! finally I found the gap should be a 0603 10kΩ resistor.
It's a good design, cause you can use the GPIO 48 for other functions.
But it is frustrating there is no document for this tip.

![esp32-s3-rgb-led-3](https://github.com/vcc-gnd/YD-ESP32-S3/assets/5326919/b5974b4e-fb4d-48b9-a1f7-6ea921a2dc6f)
![esp32-s3-rgb-led](https://github.com/vcc-gnd/YD-ESP32-S3/assets/5326919/d3793290-f7a5-4d80-9cdf-83c79b2aac7b)

**Comment by vcc-gnd** [comment]
你购买是板子是山寨板，需要短接



At 2023-06-25 03:28:19, "Shuhu Liu" ***@***.***> wrote:

It works! finally I found the gap should be a 0603 10kΩ resistor.
It's a good design, cause you can use the GPIO 48 for other functions.
But it is frustrating there is no document for this tip.
