### ISSUE TITLE
5V供电问题

### ISSUE THREAD

**Issue by zhangxiaokai007** [vcc-gnd/YD-ESP32-S3#11]
您好，我注意到P1的21管脚为5V电源，想问一下这个管脚可以通过短接IN-OUT来实现5V输出吗？

**Comment by vcc-gnd** [comment]
可以



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月05日 12:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [vcc-gnd/YD-ESP32-S3] 5V供电问题 (Issue #11) |

您好，我注意到P1的21管脚为5V电源，想问一下这个管脚可以通过短接IN-OUT来实现5V输出吗？
